// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateReferenceLink(ctx context.Context, arg CreateReferenceLinkParams) (ReferenceLink, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error)
	DeleteReferenceLink(ctx context.Context, id uuid.UUID) (ReferenceLink, error)
	ExpireUserSession(ctx context.Context, id uuid.UUID) error
	GetReferenceLinkByID(ctx context.Context, id uuid.UUID) (GetReferenceLinkByIDRow, error)
	GetReferenceLinkByToken(ctx context.Context, token string) (GetReferenceLinkByTokenRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserBySessionToken(ctx context.Context, token string) (GetUserBySessionTokenRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
