// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file user/v1/user.proto (package user.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file user/v1/user.proto.
 */
export const file_user_v1_user: GenFile = /*@__PURE__*/
  fileDesc("ChJ1c2VyL3YxL3VzZXIucHJvdG8SB3VzZXIudjEiiwEKBFVzZXISCgoCaWQYASABKAkSFwoKZ2l2ZW5fbmFtZRgCIAEoCUgAiAEBEhgKC2ZhbWlseV9uYW1lGAMgASgJSAGIAQESDQoFZW1haWwYBCABKAkSFgoOZW1haWxfdmVyaWZpZWQYBSABKAhCDQoLX2dpdmVuX25hbWVCDgoMX2ZhbWlseV9uYW1lIjAKC1VzZXJTZXNzaW9uEg0KBXRva2VuGAEgASgJEhIKCmV4cGlyZXNfYXQYAiABKAkiIAoSR2V0VXNlckJ5SWRSZXF1ZXN0EgoKAmlkGAEgASgJIjIKE0dldFVzZXJCeUlkUmVzcG9uc2USGwoEdXNlchgBIAEoCzINLnVzZXIudjEuVXNlciJ0ChFDcmVhdGVVc2VyUmVxdWVzdBIXCgpnaXZlbl9uYW1lGAEgASgJSACIAQESGAoLZmFtaWx5X25hbWUYAiABKAlIAYgBARINCgVlbWFpbBgDIAEoCUINCgtfZ2l2ZW5fbmFtZUIOCgxfZmFtaWx5X25hbWUiMQoSQ3JlYXRlVXNlclJlc3BvbnNlEhsKBHVzZXIYASABKAsyDS51c2VyLnYxLlVzZXIiLQocR2V0VXNlckJ5U2Vzc2lvblRva2VuUmVxdWVzdBINCgV0b2tlbhgBIAEoCSI8Ch1HZXRVc2VyQnlTZXNzaW9uVG9rZW5SZXNwb25zZRIbCgR1c2VyGAEgASgLMg0udXNlci52MS5Vc2VyMpACCg9JZGVudGl0eVNlcnZpY2USSgoLR2V0VXNlckJ5SWQSGy51c2VyLnYxLkdldFVzZXJCeUlkUmVxdWVzdBocLnVzZXIudjEuR2V0VXNlckJ5SWRSZXNwb25zZSIAEmgKFUdldFVzZXJCeVNlc3Npb25Ub2tlbhIlLnVzZXIudjEuR2V0VXNlckJ5U2Vzc2lvblRva2VuUmVxdWVzdBomLnVzZXIudjEuR2V0VXNlckJ5U2Vzc2lvblRva2VuUmVzcG9uc2UiABJHCgpDcmVhdGVVc2VyEhoudXNlci52MS5DcmVhdGVVc2VyUmVxdWVzdBobLnVzZXIudjEuQ3JlYXRlVXNlclJlc3BvbnNlIgBCVQoLY29tLnVzZXIudjFCCVVzZXJQcm90b1ABogIDVVhYqgIHVXNlci5WMcoCB1VzZXJcVjHiAhNVc2VyXFYxXEdQQk1ldGFkYXRh6gIIVXNlcjo6VjFiBnByb3RvMw");

/**
 * @generated from message user.v1.User
 */
export type User = Message<"user.v1.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: optional string given_name = 2;
   */
  givenName?: string;

  /**
   * @generated from field: optional string family_name = 3;
   */
  familyName?: string;

  /**
   * @generated from field: string email = 4;
   */
  email: string;

  /**
   * @generated from field: bool email_verified = 5;
   */
  emailVerified: boolean;
};

/**
 * Describes the message user.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_user_v1_user, 0);

/**
 * @generated from message user.v1.UserSession
 */
export type UserSession = Message<"user.v1.UserSession"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * @generated from field: string expires_at = 2;
   */
  expiresAt: string;
};

/**
 * Describes the message user.v1.UserSession.
 * Use `create(UserSessionSchema)` to create a new message.
 */
export const UserSessionSchema: GenMessage<UserSession> = /*@__PURE__*/
  messageDesc(file_user_v1_user, 1);

/**
 * @generated from message user.v1.GetUserByIdRequest
 */
export type GetUserByIdRequest = Message<"user.v1.GetUserByIdRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message user.v1.GetUserByIdRequest.
 * Use `create(GetUserByIdRequestSchema)` to create a new message.
 */
export const GetUserByIdRequestSchema: GenMessage<GetUserByIdRequest> = /*@__PURE__*/
  messageDesc(file_user_v1_user, 2);

/**
 * @generated from message user.v1.GetUserByIdResponse
 */
export type GetUserByIdResponse = Message<"user.v1.GetUserByIdResponse"> & {
  /**
   * @generated from field: user.v1.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message user.v1.GetUserByIdResponse.
 * Use `create(GetUserByIdResponseSchema)` to create a new message.
 */
export const GetUserByIdResponseSchema: GenMessage<GetUserByIdResponse> = /*@__PURE__*/
  messageDesc(file_user_v1_user, 3);

/**
 * @generated from message user.v1.CreateUserRequest
 */
export type CreateUserRequest = Message<"user.v1.CreateUserRequest"> & {
  /**
   * @generated from field: optional string given_name = 1;
   */
  givenName?: string;

  /**
   * @generated from field: optional string family_name = 2;
   */
  familyName?: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;
};

/**
 * Describes the message user.v1.CreateUserRequest.
 * Use `create(CreateUserRequestSchema)` to create a new message.
 */
export const CreateUserRequestSchema: GenMessage<CreateUserRequest> = /*@__PURE__*/
  messageDesc(file_user_v1_user, 4);

/**
 * @generated from message user.v1.CreateUserResponse
 */
export type CreateUserResponse = Message<"user.v1.CreateUserResponse"> & {
  /**
   * @generated from field: user.v1.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message user.v1.CreateUserResponse.
 * Use `create(CreateUserResponseSchema)` to create a new message.
 */
export const CreateUserResponseSchema: GenMessage<CreateUserResponse> = /*@__PURE__*/
  messageDesc(file_user_v1_user, 5);

/**
 * @generated from message user.v1.GetUserBySessionTokenRequest
 */
export type GetUserBySessionTokenRequest = Message<"user.v1.GetUserBySessionTokenRequest"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message user.v1.GetUserBySessionTokenRequest.
 * Use `create(GetUserBySessionTokenRequestSchema)` to create a new message.
 */
export const GetUserBySessionTokenRequestSchema: GenMessage<GetUserBySessionTokenRequest> = /*@__PURE__*/
  messageDesc(file_user_v1_user, 6);

/**
 * @generated from message user.v1.GetUserBySessionTokenResponse
 */
export type GetUserBySessionTokenResponse = Message<"user.v1.GetUserBySessionTokenResponse"> & {
  /**
   * @generated from field: user.v1.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message user.v1.GetUserBySessionTokenResponse.
 * Use `create(GetUserBySessionTokenResponseSchema)` to create a new message.
 */
export const GetUserBySessionTokenResponseSchema: GenMessage<GetUserBySessionTokenResponse> = /*@__PURE__*/
  messageDesc(file_user_v1_user, 7);

/**
 * @generated from service user.v1.IdentityService
 */
export const IdentityService: GenService<{
  /**
   * @generated from rpc user.v1.IdentityService.GetUserById
   */
  getUserById: {
    methodKind: "unary";
    input: typeof GetUserByIdRequestSchema;
    output: typeof GetUserByIdResponseSchema;
  },
  /**
   * @generated from rpc user.v1.IdentityService.GetUserBySessionToken
   */
  getUserBySessionToken: {
    methodKind: "unary";
    input: typeof GetUserBySessionTokenRequestSchema;
    output: typeof GetUserBySessionTokenResponseSchema;
  },
  /**
   * @generated from rpc user.v1.IdentityService.CreateUser
   */
  createUser: {
    methodKind: "unary";
    input: typeof CreateUserRequestSchema;
    output: typeof CreateUserResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_user_v1_user, 0);

