// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file media/v1/image.proto (package media.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file media/v1/image.proto.
 */
export const file_media_v1_image: GenFile = /*@__PURE__*/
  fileDesc("ChRtZWRpYS92MS9pbWFnZS5wcm90bxIIbWVkaWEudjEiTQoFSW1hZ2USCgoCaWQYASABKAkSCwoDdXJsGAIgASgJEg0KBXdpZHRoGAMgASgFEg4KBmhlaWdodBgEIAEoBRIMCgRzaXplGAUgASgFIicKE0dldEltYWdlQnlJZFJlcXVlc3QSEAoIaW1hZ2VfaWQYASABKAkiNgoUR2V0SW1hZ2VCeUlkUmVzcG9uc2USHgoFaW1hZ2UYASABKAsyDy5tZWRpYS52MS5JbWFnZTJfCgxJbWFnZVNlcnZpY2USTwoMR2V0SW1hZ2VCeUlkEh0ubWVkaWEudjEuR2V0SW1hZ2VCeUlkUmVxdWVzdBoeLm1lZGlhLnYxLkdldEltYWdlQnlJZFJlc3BvbnNlIgBCWwoMY29tLm1lZGlhLnYxQgpJbWFnZVByb3RvUAGiAgNNWFiqAghNZWRpYS5WMcoCCE1lZGlhXFYx4gIUTWVkaWFcVjFcR1BCTWV0YWRhdGHqAglNZWRpYTo6VjFiBnByb3RvMw");

/**
 * @generated from message media.v1.Image
 */
export type Image = Message<"media.v1.Image"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string url = 2;
   */
  url: string;

  /**
   * @generated from field: int32 width = 3;
   */
  width: number;

  /**
   * @generated from field: int32 height = 4;
   */
  height: number;

  /**
   * @generated from field: int32 size = 5;
   */
  size: number;
};

/**
 * Describes the message media.v1.Image.
 * Use `create(ImageSchema)` to create a new message.
 */
export const ImageSchema: GenMessage<Image> = /*@__PURE__*/
  messageDesc(file_media_v1_image, 0);

/**
 * @generated from message media.v1.GetImageByIdRequest
 */
export type GetImageByIdRequest = Message<"media.v1.GetImageByIdRequest"> & {
  /**
   * @generated from field: string image_id = 1;
   */
  imageId: string;
};

/**
 * Describes the message media.v1.GetImageByIdRequest.
 * Use `create(GetImageByIdRequestSchema)` to create a new message.
 */
export const GetImageByIdRequestSchema: GenMessage<GetImageByIdRequest> = /*@__PURE__*/
  messageDesc(file_media_v1_image, 1);

/**
 * @generated from message media.v1.GetImageByIdResponse
 */
export type GetImageByIdResponse = Message<"media.v1.GetImageByIdResponse"> & {
  /**
   * @generated from field: media.v1.Image image = 1;
   */
  image?: Image;
};

/**
 * Describes the message media.v1.GetImageByIdResponse.
 * Use `create(GetImageByIdResponseSchema)` to create a new message.
 */
export const GetImageByIdResponseSchema: GenMessage<GetImageByIdResponse> = /*@__PURE__*/
  messageDesc(file_media_v1_image, 2);

/**
 * @generated from service media.v1.ImageService
 */
export const ImageService: GenService<{
  /**
   * @generated from rpc media.v1.ImageService.GetImageById
   */
  getImageById: {
    methodKind: "unary";
    input: typeof GetImageByIdRequestSchema;
    output: typeof GetImageByIdResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_media_v1_image, 0);

