// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: user/v1/user.proto

package userv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/mcorrigan89/simple_auth/server/user/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// IdentityServiceName is the fully-qualified name of the IdentityService service.
	IdentityServiceName = "user.v1.IdentityService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// IdentityServiceGetUserByIdProcedure is the fully-qualified name of the IdentityService's
	// GetUserById RPC.
	IdentityServiceGetUserByIdProcedure = "/user.v1.IdentityService/GetUserById"
	// IdentityServiceGetUserBySessionTokenProcedure is the fully-qualified name of the
	// IdentityService's GetUserBySessionToken RPC.
	IdentityServiceGetUserBySessionTokenProcedure = "/user.v1.IdentityService/GetUserBySessionToken"
	// IdentityServiceCreateUserProcedure is the fully-qualified name of the IdentityService's
	// CreateUser RPC.
	IdentityServiceCreateUserProcedure = "/user.v1.IdentityService/CreateUser"
)

// IdentityServiceClient is a client for the user.v1.IdentityService service.
type IdentityServiceClient interface {
	GetUserById(context.Context, *connect.Request[v1.GetUserByIdRequest]) (*connect.Response[v1.GetUserByIdResponse], error)
	GetUserBySessionToken(context.Context, *connect.Request[v1.GetUserBySessionTokenRequest]) (*connect.Response[v1.GetUserBySessionTokenResponse], error)
	CreateUser(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error)
}

// NewIdentityServiceClient constructs a client for the user.v1.IdentityService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewIdentityServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) IdentityServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	identityServiceMethods := v1.File_user_v1_user_proto.Services().ByName("IdentityService").Methods()
	return &identityServiceClient{
		getUserById: connect.NewClient[v1.GetUserByIdRequest, v1.GetUserByIdResponse](
			httpClient,
			baseURL+IdentityServiceGetUserByIdProcedure,
			connect.WithSchema(identityServiceMethods.ByName("GetUserById")),
			connect.WithClientOptions(opts...),
		),
		getUserBySessionToken: connect.NewClient[v1.GetUserBySessionTokenRequest, v1.GetUserBySessionTokenResponse](
			httpClient,
			baseURL+IdentityServiceGetUserBySessionTokenProcedure,
			connect.WithSchema(identityServiceMethods.ByName("GetUserBySessionToken")),
			connect.WithClientOptions(opts...),
		),
		createUser: connect.NewClient[v1.CreateUserRequest, v1.CreateUserResponse](
			httpClient,
			baseURL+IdentityServiceCreateUserProcedure,
			connect.WithSchema(identityServiceMethods.ByName("CreateUser")),
			connect.WithClientOptions(opts...),
		),
	}
}

// identityServiceClient implements IdentityServiceClient.
type identityServiceClient struct {
	getUserById           *connect.Client[v1.GetUserByIdRequest, v1.GetUserByIdResponse]
	getUserBySessionToken *connect.Client[v1.GetUserBySessionTokenRequest, v1.GetUserBySessionTokenResponse]
	createUser            *connect.Client[v1.CreateUserRequest, v1.CreateUserResponse]
}

// GetUserById calls user.v1.IdentityService.GetUserById.
func (c *identityServiceClient) GetUserById(ctx context.Context, req *connect.Request[v1.GetUserByIdRequest]) (*connect.Response[v1.GetUserByIdResponse], error) {
	return c.getUserById.CallUnary(ctx, req)
}

// GetUserBySessionToken calls user.v1.IdentityService.GetUserBySessionToken.
func (c *identityServiceClient) GetUserBySessionToken(ctx context.Context, req *connect.Request[v1.GetUserBySessionTokenRequest]) (*connect.Response[v1.GetUserBySessionTokenResponse], error) {
	return c.getUserBySessionToken.CallUnary(ctx, req)
}

// CreateUser calls user.v1.IdentityService.CreateUser.
func (c *identityServiceClient) CreateUser(ctx context.Context, req *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error) {
	return c.createUser.CallUnary(ctx, req)
}

// IdentityServiceHandler is an implementation of the user.v1.IdentityService service.
type IdentityServiceHandler interface {
	GetUserById(context.Context, *connect.Request[v1.GetUserByIdRequest]) (*connect.Response[v1.GetUserByIdResponse], error)
	GetUserBySessionToken(context.Context, *connect.Request[v1.GetUserBySessionTokenRequest]) (*connect.Response[v1.GetUserBySessionTokenResponse], error)
	CreateUser(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error)
}

// NewIdentityServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewIdentityServiceHandler(svc IdentityServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	identityServiceMethods := v1.File_user_v1_user_proto.Services().ByName("IdentityService").Methods()
	identityServiceGetUserByIdHandler := connect.NewUnaryHandler(
		IdentityServiceGetUserByIdProcedure,
		svc.GetUserById,
		connect.WithSchema(identityServiceMethods.ByName("GetUserById")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceGetUserBySessionTokenHandler := connect.NewUnaryHandler(
		IdentityServiceGetUserBySessionTokenProcedure,
		svc.GetUserBySessionToken,
		connect.WithSchema(identityServiceMethods.ByName("GetUserBySessionToken")),
		connect.WithHandlerOptions(opts...),
	)
	identityServiceCreateUserHandler := connect.NewUnaryHandler(
		IdentityServiceCreateUserProcedure,
		svc.CreateUser,
		connect.WithSchema(identityServiceMethods.ByName("CreateUser")),
		connect.WithHandlerOptions(opts...),
	)
	return "/user.v1.IdentityService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case IdentityServiceGetUserByIdProcedure:
			identityServiceGetUserByIdHandler.ServeHTTP(w, r)
		case IdentityServiceGetUserBySessionTokenProcedure:
			identityServiceGetUserBySessionTokenHandler.ServeHTTP(w, r)
		case IdentityServiceCreateUserProcedure:
			identityServiceCreateUserHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedIdentityServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedIdentityServiceHandler struct{}

func (UnimplementedIdentityServiceHandler) GetUserById(context.Context, *connect.Request[v1.GetUserByIdRequest]) (*connect.Response[v1.GetUserByIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.v1.IdentityService.GetUserById is not implemented"))
}

func (UnimplementedIdentityServiceHandler) GetUserBySessionToken(context.Context, *connect.Request[v1.GetUserBySessionTokenRequest]) (*connect.Response[v1.GetUserBySessionTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.v1.IdentityService.GetUserBySessionToken is not implemented"))
}

func (UnimplementedIdentityServiceHandler) CreateUser(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("user.v1.IdentityService.CreateUser is not implemented"))
}
